
-- REGIONAL_HUB table
CREATE TABLE REGIONAL_HUB (
    REGI_ID SERIAL PRIMARY KEY UNIQUE,
    NAME VARCHAR(255),
    CITY_NAME VARCHAR(255)
);

-- DRIVER table
CREATE TABLE DRIVER (
    D_ID SERIAL PRIMARY KEY,
    D_NAME VARCHAR(255),
    LICENSE VARCHAR(50),
    REGI_ID INT REFERENCES REGIONAL_HUB(REGI_ID)
);

-- VEHICLES table
CREATE TABLE VEHICLES (
    V_ID SERIAL PRIMARY KEY,
    V_TYPE VARCHAR(50),
    D_ID INT REFERENCES DRIVER(D_ID),
    STATUS VARCHAR(50),
    REGI_ID INT REFERENCES REGIONAL_HUB(REGI_ID),
    CURRENT_ZONE VARCHAR(100),
    BASE_FARE VARCHAR(50)
);

-- CUSTOMER table
CREATE TABLE CUSTOMER (
    CUS_ID SERIAL PRIMARY KEY,
    CUS_NAME VARCHAR(255),
    CUS_PHONE VARCHAR(50),
    CUS_EMAIL VARCHAR(255)
);

-- RIDE table
CREATE TABLE RIDE (
    R_ID SERIAL PRIMARY KEY,
    CUSTOMER_ID INT REFERENCES CUSTOMER(CUS_ID),
    V_ID INT REFERENCES VEHICLES(V_ID),
    DISTANCE VARCHAR(50),
    START_TIME BIGINT,
    END_TIME BIGINT,
    FARE VARCHAR(50),
    DESTINATION VARCHAR(255)
);

-- FEEDBACK table
CREATE TABLE FEEDBACK (
    FEED_ID SERIAL PRIMARY KEY,
    R_ID INT REFERENCES RIDE(R_ID),
    RATING VARCHAR(10),
    COMMENT VARCHAR(500)
);

-- PAYMENT table
CREATE TABLE PAYMENT (
    PAYMENT_ID SERIAL PRIMARY KEY,
    R_ID INT REFERENCES RIDE(R_ID),
    TYPE VARCHAR(50),
    PAYMENT_AC VARCHAR(50),
    PAY_STATUS VARCHAR(50),
    PAY_DATE_TIME VARCHAR(50)
);
